intl: Fix clang -Wunused-but-set-variable on plural.c
Clang warns that '__gettextnerrs' set but not used:

  intl/plural.c:1034:9: error: variable '__gettextnerrs' set but not used
  [-Werror,-Wunused-but-set-variable]
      int yynerrs = 0;
        ^

Clang 15 (https://reviews.llvm.org/D122271) -Wunused-but-set-variable
gives a warning while GCC doesn't.  The -Wunused-but-set-variable is
available in GCC 4.6, lower than the minimum required version 6.2.

Since the file is auto-generated, suppress the warning with a compiler
flag.

Reviewed-by: Fangrui Song <maskray@google.com>