Fix building support_ptrace.c on i686-gnu.
On i686-gnu the build is broken:
In file included from support_ptrace.c:22:
../include/sys/prctl.h:2:15: fatal error: sys/prctl.h: No such file or directory
 #include_next <sys/prctl.h>

This patch just removes the unused prctl.h inclusion.

ChangeLog:

	* support/support_ptrace.c: Remove inclusion of sys/prctl.h.