Get rid of duplicate const declaration specifier warning in tst-resolv-qtypes.c.
Compiling resolv/tst-resolv-qtypes.c with GCC 7 results in:
tst-resolv-qtypes.c:53:14: error: duplicate ‘const’ declaration specifier [-Werror=duplicate-decl-specifier]
 static const const char *domain = "www.example.com";

This patch removes the duplicate const and makes domain a const pointer
to const char literal.

ChangeLog:

	* resolv/tst-resolv-qtypes.c (domain):
	Change type to const pointer to const char.

(cherry picked from commit d4f94368a96541db2b38b6535402a941f5aff975)