Use -Wno-error=trampolines
With gcc 4.9 we see

tst-execstack-mod.c: In function ‘tryme’:
tst-execstack-mod.c:16:8: error: trampoline generated for nested function ‘callback’ [-Werror=trampolines]
   void callback (void) { ok = true; }
           ^
	   cc1: all warnings being treated as errors

where of course the testcases require the use of trampolines.