sunrpc: Remove extra parenthesis on comparison
clang issues:

key_call.c:459:20: error: equality comparison with extraneous parentheses [-Werror,-Wparentheses-equality]
  459 |   if ((kcp->client == (CLIENT *) NULL))

Instead of suppress the warning, just use the more usual comparison style.